apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3 # Tells Kubernetes to always keep 3 copies runihng
  selector: # The selector is how the deployment finds which pods to manage
    matchLabels:
      app: python-app
  template: # The template is the blueprint for the pods that will be created
    metadata: 
      labels: # The labels are used to identify the pods that belong to this deployment
        app: python-app
    spec:
      containers:
      - name: python-container
        image: host.minikube.internal:5000/python-devsecops-registry/python-app:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: nexus-auth
