apiVersion: v1
kind: Service
metadata: 
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: chaos-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000